### ISSUE TITLE
Design download page to include Data description, brief description of project, contact info.

### ISSUE THREAD

**Issue by mmazanec22** [codefordayton/floswhistle-pandemic-v2#38]
Button link to DOWNLOAD 
Hyperlink to email for flo@codefordayton.org

**Comment by mmazanec22** [comment]
Button color the lighter/turquoise color from the logo? #00b3e6

**Comment by c-malecki** [comment]
Most recent design of sorts for download page
https://xd.adobe.com/view/ac2680f4-8f06-4a09-4c90-b0f976e5d213-da17/
